# Generated by Django 2.2 on 2021-03-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icecream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
